application: muntjac-sampler
version: 1
runtime: python
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: muntjac.demo.gae.py
#  script: muntjac.demo.gae.app

- url: /VAADIN
  static_dir: /
